#!/usr/bin/fish

set tmpfile (mktemp --tmpdir i3lock-wrapper-XXXXXXXXXX.png)
set outfile (mktemp --tmpdir i3lock-wrapper-XXXXXXXXXX.png)
scrot $tmpfile
convert $tmpfile -scale 20% -scale 500% $outfile
i3lock -i $outfile
rm $tmpfile $outfile
