#!/usr/bin/fish

set tmpfile (mktemp --tmpdir i3lock-wrapper-XXXXXXXXXX.png)
set outfile (mktemp --tmpdir i3lock-wrapper-XXXXXXXXXX.png)

scrot $tmpfile
mogrify -resize 50% -resize 200% -blur 0x4 $tmpfile

if test 1 -lt (count (xrandr --query | ag " connected"))
    i3lock -i $tmpfile
else
    convert -gravity center -composite $tmpfile $XDG_CONFIG_HOME/i3/i3lock.png $outfile
    i3lock -u -i $outfile
end

rm $tmpfile $outfile
