((magit-fetch "--prune" "--tags" "--force")
 (magit-log:magit-log-mode "-n256" "--graph" "--color" "--decorate")
 (magit-rebase "--autostash")
 (magit-stash "--include-untracked")
 (magit-submodule "--force" "--remote"))
