;;(package-initialize)
(add-to-list 'load-path "~/.emacs.d/init")
(require 'packages-cfg)
(require 'functions-cfg)
(require 'shell-cfg)
(require 'misc-settings-cfg)
(require 'helm-cfg)
(require 'evil-cfg)
(require 'avy-cfg)
(require 'company-cfg)
(require 'latex-cfg)
(require 'magit-cfg)
(require 'org-mode-cfg)
(require 'modeline-cfg)
(require 'diminish-cfg)
(require 'flycheck-cfg)
(require 'dired-cfg)
(require 'python-cfg)
(require 'haskell-cfg)
(require 'projectile-cfg)
(require 'keybinds-cfg)
