;;(package-initialize)
(add-to-list 'load-path "~/.emacs.d/init")
(require 'preload-cfg)
(require 'packages-cfg)
(require 'misc-settings-cfg)
(require 'functions-cfg)
(require 'evil-cfg)
(require 'helm-cfg)
(require 'shell-cfg)
(require 'avy-cfg)
(require 'company-cfg)
(require 'magit-cfg)
(require 'org-mode-cfg)
(require 'modeline-cfg)
(require 'flycheck-cfg)
(require 'dired-cfg)
(require 'python-cfg)
(require 'cpp-cfg)
(require 'pdf-cfg)
(require 'projectile-cfg)
(require 'smartparens-cfg)
(require 'fish-cfg)
(require 'i3-config-mode-cfg)
(require 'compile-cfg)
(require 'keybinds-cfg)
(require 'shackle-cfg)
(require 'local-cfg)

;; (require 'rust-cfg)
;; (require 'latex-cfg)
;; (require 'haskell-cfg)
